# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_first_library',
                'doc_host': 'https://akarim23131.github.io',
                'git_url': 'https://github.com/akarim23131/my_first_library',
                'lib_path': 'my_first_library'},
  'syms': {'my_first_library.core': {'my_first_library.core.foo': ('core.html#foo', 'my_first_library/core.py')}}}
